### ISSUE TITLE
App is not working in dev mode

### ISSUE THREAD

**Issue by LakeVostok** [gravity-ui/landing#77]
node v18.16.0
![123](https://github.com/gravity-ui/landing/assets/17967390/5092edbe-bae5-414e-8935-d7dded1b6cdd)
![456](https://github.com/gravity-ui/landing/assets/17967390/363b2b2f-283b-44d8-ac0a-797c78e836a9)

**Comment by imsitnikov** [comment]
@LakeVostok are you getting this error on Windows?
I can't reproduce this error on MacOS 14.4.1 and Ubuntu 20.04.6.

**Comment by makhnatkin** [comment]
@LakeVostok by .nvmrc requires version `18.17.0`
Try to run `nvm use` and if necessary `npm install 18.17.0`

Is there an error in this case?
